server:
  port: 8082
    
## MySQL

spring: 
  datasource: 
         url: jdbc:mysql://customer.cwdg9ienxrky.ap-south-1.rds.amazonaws.com:3306/customer
         username: root
         password: admin321
  jpa:
    hibernate:
         ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect